### PR TITLE
fix build on macOS

### PR DESCRIPTION
**Pull request by Shieldine**
This PR fixes the failing build on macOS. It seems to have been caused by removing the explicit setting of a cpp standard in the main CMakeLists.txt

It's now set to 20 as it was in previous commits

### CODE REVIEW

**Comment by lfreist** [comment]
@Shieldine can you elaborate, why C++20 is needed for macOS? hwinfo builds with C++11 on Windows and Linux... Or is it just that the used standard must be set?

**Comment by Shieldine** [comment]
@lfreist it's just that a standard must be set or macOS will take something below 11 and thus fail to build.
Looking at previous commits, c++20 was defined. If 11 is enough, i can gladly change to 11. We just need something that is 11 or above

**Comment by lfreist** [comment]
Thank you! Yes, please set it to 11 then. The plan is, that the first release is C++11 and later releases introduce more modern features. I want to make sure that a working version is available for C++11 compilers...

**Comment by Shieldine** [comment]
@lfreist Way ahead of you! :) C++11 already passed the pipeline, ready to merge

**Pull request merged**
