### PR TITLE
Added `Available Memory` module to Linux

### PR DESCRIPTION
**Pull request by Ace-Krypton**
I only added Linux for now, I don't have windows laptop on me right now so I will add it later on

### CODE REVIEW

**Comment by Ace-Krypton** [comment]
I added dummy methods, if there is something else wrong sorry, I am not good at this kinda styling, just tried to help with something :)

**Comment by lfreist** [comment]
You just returned a string from a function that must return an integer. Please return -1 instead of "<unknown>" and it is fine.

Thanks for your efforts!

**Comment by Ace-Krypton** [comment]
my bad lol, I was kinda tired at that time, anyways this should be fine

**Comment by Ace-Krypton** [comment]
last one should be okay, anyways thanks, I will fill out those dummy methods too, in few weeks

**Pull request merged**
