### PR TITLE
fixbug: add wstring_to_std_tring, to fix disk._vendor decode bug, support getAvailableMemory on windows 

### PR DESCRIPTION
**Pull request by liguobao**
the code ”{tmp.begin(), tmp.end()}; “ decode fail on Windows.

it return " (屏豵╤)"，

the right text is “ (标准磁盘驱动器)”.

--------------------------------- Disks -----------------------------------
Disk 0:
  vendor:           (屏豵╤)
  model:            Samsung SSD 980 1TB
  serial-number:    
  size:             -1
Disk 1:
  vendor:           (屏豵╤)
  model:            WDC WD10EZEX-00BBHA0
  serial-number:         
  size:             -1
---------------------------------------------------------------------------

## I had fix it.

----------------------------------- RAM -----------------------------------
vendor:             A-DATA Technology
model:
name:               物理内存
serial-number:      7D950300
size [MiB]:         65277.4
free [MiB]:         -9.53674e-07
------------------------------- Main Board --------------------------------
vendor:             ASUSTeK COMPUTER INC.
name:               PRIME Z690-P D4
version:            Rev 1.xx
serial-number:      7D950300
------------------------------- Batteries ---------------------------------
No Batteries installed or detected
--------------------------------- Disks -----------------------------------
Disk 0:
  vendor:           (标准磁盘驱动器)
  model:            Samsung SSD 980 1TB
  serial-number:    
  size:             -1
Disk 1:
  vendor:           (标准磁盘驱动器)
  model:            WDC WD10EZEX-00BBHA0
  serial-number:         
  size:             -1

### CODE REVIEW

**Comment by lfreist** [comment]
Hi, thank you for your contribution and fix.
Please make sure, the code style gets fixed (c.f. GitHub action)

**Comment by liguobao** [comment]
> Hi, thank you for your contribution and fix. Please make sure, the code style gets fixed (c.f. GitHub action)

OK, I fix it.

**Comment by liguobao** [comment]
> Hi! The result you posted looks good. However, the build fails for Linux (gcc and clang) and Windows (Visual Studio and MinGW). Also the code style requirements are not met yet.

OK, I had fix it~

**Comment by liguobao** [comment]
Please approval the workflows~
Thanks~~~

**Comment by liguobao** [comment]
I support getAvailableMemory on windows, please merge it.

https://github.com/lfreist/hwinfo/pull/27/commits/342ad7baa30489a81ae48ef037a7a813ef508ab4

**Comment by liguobao** [comment]
All Action is passed, please merge it~
Good night~

**Pull request merged**
